#:schema node_modules/wrangler/config-schema.json
name = "gaasublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "ffece8ec7f2f49a9a3703325e966310a" }
]

[assets]
directory = "./public"
